server:
  port: 9000
  shutdown: immediate

spring:
  boot:
    admin:
      client:
        url:
          - http://127.0.0.1:9000
  application:
    name: Spring Boot Admin

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    access:
      default: unrestricted
    web:
      exposure:
        include: "*"
